### PR TITLE
Make base64url encode decode public and allow base64url encoded ids…

### PR DESCRIPTION
**Pull request by theroch**
…, challenges etc.

This changes make the php backend server compatible to JS WebAuthnApp
https://github.com/apowers313/webauthn-simple-app

Signed-off-by: Frank Rochlitzer <f.rochlitzer@b3-it.de>

### CODE REVIEW

**Comment by lbuchs** [comment]
You cannot simply add RS256  algorithm to the create args if the backend (class AuthenticatorData) cannot handle RS256. It's only tested with ES256, haven't analyzed yet what's to be done to accept RSA.

**Comment by theroch** [comment]
> You cannot simply add RS256 algorithm to the create args if the backend (class AuthenticatorData) cannot handle RS256. It's only tested with ES256, haven't analyzed yet what's to be done to accept RSA.
Ok, I didn't look that deep into the code. I can remove the RS256 algorithm.
But is the rest of my modifications acceptable for you?

**Comment by theroch** [comment]
Is the code now acceptable?

**Comment by lbuchs** [comment]
well actually I'm not happy how the implementation of base64 url to transfer binary data is done. It should still use the ByteBuffer class, the change of the format should happen in the jsonSerialize interface of the Binary\ByteBuffer class.

**Comment by lbuchs** [comment]
base64 url for binary strings commited in 27a07e42496d4fa14.

**Pull request closed without merging**
